### ISSUE TITLE
Multiple docker registries

### ISSUE THREAD

**Issue by rturam** [aluc-io/gitlab-runner-with-ecr#2]
Hi,

How to use multiple docker registries(urls) with this setup. Ex. If we have different registries for different environments.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
Hello,

If you need multiple AWS Access keys to access multiple ECRs, you may need to run multiple `gitlab-runner-with-ecr` Docker Containers.

**Comment by arnuschky** [comment]
Can I simply execute several `get` commands for each registry if the permissioning is taken care of  by IAM profiles?

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@arnuschky 

I'm not sure, but remember that when you use a profile (IAM Role) or AWS Access key that has access to multiple ECRs, you only need to run the `get` command the first time. The next time another ECR was used, `amazon-ecr-credential-helper` would automatically login. (This part needs to be checked again.)

It was a weird part, but when I have time, I'll check it out and update README.

**Comment by arnuschky** [comment]
Thanks @b6pzeusbc54tvhw5jgpyw8pwz2x6gs I'll try that.
