### ISSUE TITLE
How to use this with docker-machine?

### ISSUE THREAD

**Issue by arnuschky** [aluc-io/gitlab-runner-with-ecr#3]
I am not sure how I would need to configure this runner to work with auto-scaling runner instances via the docker+machine executor.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
Currently, in README.md, only `4. docker-credential-ecr-login get` part should be manually executed.

If you can parameterize the ECR address of the command below and automatically execute this command after Instances are created, it is likely to be available in the instance being autoscaled.

```shell
$ docker-compose exec -T runner /bin/sh -c "echo <ECR address> | docker-credential-ecr-login get"
```

Other ways, maybe we have a way to share the `~/.ecr` directory, but I didn't check yet.

**Comment by arnuschky** [comment]
This actually worked for fine me in the end.

(My problem was due to an unrelated configuration issue.)
